# Generated by Django 6.0.1 on 2026-02-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_markers_alter_story_modified_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='story',
            table='tbl_story',
        ),
    ]
