# Generated by Django 6.0.2 on 2026-02-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='writerId',
            new_name='writer',
        ),
    ]
