# Generated by Django 6.0.2 on 2026-02-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rename_writerid_story_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='writer',
            new_name='writerId',
        ),
    ]
