# Generated by Django 6.0.2 on 2026-02-21 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_rename_writer_story_writerid'),
        ('writers', '0005_rename_writer_id_writer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='writerId',
            field=models.ForeignKey(db_column='writer_id', on_delete=django.db.models.deletion.RESTRICT, to='writers.writer'),
        ),
    ]
