# Generated by Django 6.0.1 on 2026-02-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='writer',
            table='tbl_writer',
        ),
    ]
