# Generated by Django 6.0.2 on 2026-02-21 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_alter_writer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='login',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
