# Generated by Django 6.0.2 on 2026-02-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0003_alter_writer_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='id',
            new_name='writer_id',
        ),
    ]
