# Generated by Django 6.0.2 on 2026-02-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0004_rename_id_writer_writer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='writer_id',
            new_name='id',
        ),
    ]
